
schema;node_list:
  type: seq
  required: false
  sequence:
  - type: map
    mapping:
      "host": { type: str, required: true}
      "hostname": { type: str}
      "vmname": { type: str}
      "root_volume_index": { type: int }
      "data_volume_index": { type: int, required: false}
      "data_volume_indexes":
        type: seq 
        required: false
        sequence:
        - type: int


type: map
mapping:
  "zone": { type: str, required: false, unique: yes }
  "kvm_template": { type: str, required: false, unique: yes }

  "roles":
    type: seq
    required: true
    sequence:
    - type: map
      mapping:
        "root_lvs":
          type: seq
          required: true
          sequence:
          - type: map
            mapping:
              "name": { type: str, required: true}
              "size": { type: int, required: true}
        "zone": { type: str, required: false, unique: yes }
        "kvm_template": { type: str, required: false, unique: yes }
        "data_disks":
          type: seq 
          required: false
          sequence:
          - type: map
            mapping:
              "size": { type: int, required: true }
              "mount": { type: str, required: false }
              "mode": { type: str, required: true, enum: [ 'thin', 'thick' ]  }



    