

type: map
mapping:
  "id": { type: str, required: true, unique: yes }
  "domain": { type: str, required: false, unique: yes }
  "zone": { type: str, required: false, unique: yes }
  "kvm_template": { type: str, required: false, unique: yes }

  "patterns":
    type: seq
    required: true
    sequence:
    - type: map
      mapping:
        "name": { type: str, required: true}
        "vcpu": { type: int, required: true}
        "memory": { type: int, required: true}
        "root_disk":
          type: map
          required: true
          mapping:
            "slash": { type: int, required: true }
            "varlog": { type: int, required: true }
            "swap": { type: int, required: true }
        "zone": { type: str, required: false, unique: yes }
        "domain": { type: str, required: false, unique: yes }
        "kvm_template": { type: str, required: false, unique: yes }
        


  "nodes":
    type: seq
    required: true
    sequence:
    - type: map
      mapping:
        "name": { type: str, required: true}
        "host": { type: str, required: true}
        "pattern": { type: str, required: true}
        "hostname": { type: str}
        "vmname": { type: str}
        "root_volume_index": { type: int }
        
