
type: map
mapping:
  "role_paths":
    type: seq
    required: false
    sequence:
    - type: str  

  "groups":
     type: seq
     required: false
     sequence:
     - type: map
       mapping: 
        "name": { type: str, required: true}
        "hosts":
          type: seq
          required: true
          sequence:
          - type: str             
  
