
type: map
mapping:
  "plugins_paths":
    type: seq
    required: true
    sequence:
    - type: str
  "vaults":
    type: seq
    required: false
    sequence:
    - type: map
      mapping:
        "vault_id": { type: str, required: true }
        "password_file": { type: str, required: true }
        "safe_config_file": { type: str, required: false }
             
    
    
    
  
