
type: map
mapping:
  "plugins_paths":
    type: seq
    required: true
    sequence:
    - type: str
  "vault_password_files":
    type: seq
    required: false
    sequence:
    - type: map
      mapping:
        "vault_id": { type: str, required: true }
        "file": { type: str, required: true }
             
    
    
    
  
